### ISSUE TITLE
字体CDN

### ISSUE THREAD

**Issue by ShadowRZ** [ShadowRZ/shadowrz.github.io#1]
如题。
@clarkzjw @biergaizi

**Comment by ShadowRZ** [comment]
算了，换用Jekyll就不用考虑这么多了。

**Comment by biergaizi** [comment]
CDN 这东西是大型互联网企业跨网络跟踪用户浏览信息的首选，老大哥的最爱。如果有条件自己托管就别 CDN 了，只有在真正有必要的时候再用 CDN，其他任何需要从别的服务器上获取的资源也同理。我的博客就是按这个标准搭建的，你用浏览器的网络调试，看不到任何第三方资源。

**Comment by ShadowRZ** [comment]
@biergaizi 难道你还不知道我有Decentraleyes大法吗？
