### ISSUE TITLE
DPlayer，APlayer和WebTorrent等的iframe嵌入是否可行

### ISSUE THREAD

**Issue by ShadowRZ** [ShadowRZ/shadowrz.github.io#3]
@biergaizi @clarkzjw @DIYgod
[DPlayer](https://github.com/DIYgod/DPlayer)，[APlayer](https://github.com/DIYgod/APlayer)和[WebTorrent](https://webtorrent.io)都是不错的项目，但是需要加载JS脚本。而我的要求是：在**不使用**自定义布局文件的情况下嵌入它们。
`<iframe>`嵌入方法可行吗？

**Comment by kittgo** [comment]
我只想知道你和@breakwa11是什么关系，还有你的头像  (迷

**Comment by ShadowRZ** [comment]
我只知道@breakwa11是神器ShadowsocksR的作者，我并没有和TA搭话过。

至于头像是真人。

于 2017年6月8日 GMT+08:00下午12:47:57, Aaron Li <notifications@github.com> 写到:
>我只想知道你和@breakwa11是什么关系，还有你的头像  (迷
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShadowRZ/shadowrz.github.io/issues/3#issuecomment-306997201

-- 
使用 K-9 Mail 发送自我的Android设备。

**Comment by breakwa11** [comment]
灵魂互换是什么鬼

**Comment by ShadowRZ** [comment]
@breakwa11
你的问题请转到 #5
