### ISSUE TITLE
关于与breakwa11灵魂互换的声明

### ISSUE THREAD

**Issue by ShadowRZ** [ShadowRZ/shadowrz.github.io#5]
我声明一下（_虽然我应该道歉_）：
这是因为我错过了《你的名字。》神剧才干出来的。本来以为TA不会在意，没想到居然如此在意：https://github.com/ShadowRZ/shadowrz.github.io/issues/3#issuecomment-307399142
下次还是不要这样为好。。。
@breakwa11

**Comment by ShadowRZ** [comment]
@breakwa11 向你道歉。

**Comment by breakwa11** [comment]
为什么想到要和我灵魂互换

**Comment by biergaizi** [comment]
2333333333333333333333

**Comment by biergaizi** [comment]
主要还是发的日期不对，应该 4 月 1 日发送。
